Repository sonic-net/sonic-platform-common, pull requests merged in 2019-07, with the labels that each got.

#35 [ChassisBase] Make reboot cause constant strings human-readable
  sonic_platform_base/chassis_base.py
Labels: Enhancement, Request for 201811 Branch

#37 sonic_sfp: avoid possible key error in get_physical_to_logical()
  sonic_sfp/sfputilbase.py
Labels: Bug

#39 [psu_base] get_status_led() returns current state of the status LED
  sonic_platform_base/fan_base.py
  sonic_platform_base/psu_base.py
Labels: Enhancement

#44 readd type_abbrv_name in sonic_sfp/sff8436.py
  sonic_sfp/sff8436.py
Labels: Bug

#45 Add parser support for Tx_RxLos,TxFault, PowerControl, ResetStatus in sff8436.py
  sonic_platform_base/sfp_base.py
  sonic_platform_base/sonic_sfp/sff8436.py
  sonic_sfp/sff8436.py
Labels: Enhancement
