Repository sonic-net/sonic-platform-common, pull requests merged in 2020-05, with the labels that each got.

#85 [eeprom] Add try-except to catch the IOError
  sonic_platform_base/sonic_eeprom/eeprom_base.py
Labels: Enhancement, Request for 201911 Branch

#87 [201911][component]: Introduce new firmware management API
  sonic_platform_base/component_base.py
Labels: Enhancement

#72 [sfputilbase | sfputilhelper] Add support of platform.json
  sonic_platform_base/sonic_sfp/sfputilbase.py
  sonic_platform_base/sonic_sfp/sfputilhelper.py
Labels: Enhancement, Port Breakout :trident:
