Repository sonic-net/sonic-platform-common, pull requests merged in 2020-07, with the labels that each got.

#92 Changes in fan and psu base classes (1.0 platform API) related to pddf_2.0
  sonic_fan/fan_base.py
  sonic_psu/psu_base.py
Labels: Enhancement

#93 [eeprom] Fix UnboundLocalError
  sonic_platform_base/sonic_eeprom/eeprom_base.py
Labels: Bug, EEPROM

#101 [Transceiver] Add parser for QSFP-DD cable type and dictionaries for QSFP-DD codes
  sonic_platform_base/sfp_base.py
  sonic_platform_base/sonic_sfp/qsfp_dd.py
  sonic_platform_base/sonic_sfp/sff8024.py
Labels: Enhancement, Transceiver

#104 [sfputilbase.py] Add application_advertisement N/A field to transceiver_info_dict for platform api 1.0
  sonic_platform_base/sonic_sfp/sfputilbase.py
Labels: Enhancement

#105 [bug fix] fix import issue for python3 whl building
  sonic_platform_base/sonic_sfp/qsfp_dd.py
Labels: Bug, Included in 201911 Branch, Transceiver
