Repository sonic-net/sonic-platform-common, pull requests merged in 2020-08, with the labels that each got.

#108 [Cables] Add support for 'Extended Specification Compliance' for QSFP cables
  sonic_platform_base/sonic_sfp/sff8024.py
  sonic_platform_base/sonic_sfp/sff8436.py
Labels: Enhancement, Transceiver

#103 Migrate from sonic-daemon-base package to sonic-py-common package
  setup.py
  sonic_platform_base/sonic_sfp/sfputilbase.py
  sonic_platform_base/sonic_sfp/sfputilhelper.py
Labels: Cleanup, Enhancement, Transceiver

#109 Remove sonic-config-engine dependency from setup.py
  setup.py
Labels: Bug

#112 Parse 'Extended Specification compliance' as independent field
  sonic_platform_base/sonic_sfp/sff8436.py
Labels: Bug, Enhancement, Transceiver

#100 Sfputil base and helper class changes for multi-ASIC
  sonic_platform_base/sonic_sfp/sfputilbase.py
  sonic_platform_base/sonic_sfp/sfputilhelper.py
Labels: Enhancement, Multi-ASIC, Transceiver

#115 [sff8472.py] Make hex keys all lowercase
  sonic_platform_base/sonic_sfp/sff8472.py
Labels: Bug, Request for 201911 Branch, Transceiver

#116 [sfputilbase|sfputilhelper] fix value unpack error due to port_alias_map in portconfig.py file
  sonic_platform_base/sonic_sfp/sfputilbase.py
  sonic_platform_base/sonic_sfp/sfputilhelper.py
Labels: Bug, Transceiver
