Repository sonic-net/sonic-platform-common, pull requests merged in 2020-06, with the labels that each got.

#81 [sfputilbase.py] Don't try to print EEPROM sysfs file name if we failed to read from it
  sonic_platform_base/sonic_sfp/sfputilbase.py
Labels: Request for 201911 Branch

#90 [thermal control] Backport changes from master to 201911 branch
  .gitignore
  setup.py
  sonic_platform_base/chassis_base.py
  sonic_platform_base/sonic_thermal_control/__init__.py
  sonic_platform_base/sonic_thermal_control/thermal_action_base.py
  sonic_platform_base/sonic_thermal_control/thermal_condition_base.py
  sonic_platform_base/sonic_thermal_control/thermal_info_base.py
  sonic_platform_base/sonic_thermal_control/thermal_json_object.py
  sonic_platform_base/sonic_thermal_control/thermal_manager_base.py
  sonic_platform_base/sonic_thermal_control/thermal_policy.py
  sonic_platform_base/thermal_base.py
Labels: Enhancement, Included in 201911 Branch

#91 [chassis_base] Add platform API support for system LED
  sonic_platform_base/chassis_base.py
Labels: Enhancement

#97 [sfp] Tweak key names of some transceiver info fields
  sonic_platform_base/sfp_base.py
  sonic_platform_base/sonic_sfp/sfputilbase.py
Labels: Enhancement, Request for 201911 Branch

#98 [sfp_base] Update return value documentation of channel-specific methods
  sonic_platform_base/sfp_base.py
Labels: Enhancement

#96 [sfputil] Make SfpUtilHelper.get_physical_to_logical noexcept as in SfpUtilBase
  sonic_platform_base/sonic_sfp/sfputilhelper.py
Labels: Enhancement, Request for 201911 Branch

#99 [SfpBase] Fix key name typo in docstring
  sonic_platform_base/sfp_base.py
Labels: Cleanup, Request for 201911 Branch
