Repository sonic-net/sonic-platform-common, pull requests merged in 2020-09, with the labels that each got.

#120 [setup.py] Update dependencies
  setup.py
Labels: Enhancement

#111 Fix fp_port_index error to get correct index type
  sonic_platform_base/sonic_sfp/sfputilbase.py
  sonic_platform_base/sonic_sfp/sfputilhelper.py
Labels: Bug, Transceiver

#121 [EEPROM] Add new function part_number_str to TlvInfoDecoder
  sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
Labels: EEPROM, Enhancement
