Repository sonic-net/sonic-platform-common, pull requests merged in 2020-12, with the labels that each got.

#146 Fix some LGTM alerts; Add LGTM badges to README.md
  README.md
  sonic_platform_base/sonic_eeprom/eeprom_base.py
  sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
  sonic_platform_base/sonic_sfp/bcmshell.py
  sonic_platform_base/sonic_sfp/sff8436.py
  sonic_platform_base/sonic_sfp/sff8472.py
  sonic_platform_base/sonic_sfp/sffbase.py
  sonic_platform_base/sonic_sfp/sfputilbase.py
  sonic_platform_base/sonic_sfp/sfputilhelper.py
  sonic_platform_base/thermal_base.py
Labels: Cleanup, Documentation

#148 Modular Chassis - Midplane monitoring APIs
  sonic_platform_base/chassis_base.py
  sonic_platform_base/module_base.py
Labels: Chassis, Enhancement, Module

#151 [sonic_y_cable] add check_mux_direction api for y_cable
  sonic_y_cable/y_cable.py
Labels: Bug

#152 Make eeprom_tlvinfo.py Python3 compatible
  sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
Labels: Bug, EEPROM

#153 Enhance the y_cable driver to support hook y_cable_simulator_client
  sonic_y_cable/y_cable.py
Labels: Enhancement, Transceiver

#155 Fixed eeprom_tlvinfo.py to make it Python2/Python3 compatible
  sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
Labels: Bug, EEPROM

#156 [sffbase.py] Fix to make Python 3-compatible
  sonic_platform_base/sonic_sfp/sffbase.py
Labels: Transceiver
