Repository sonic-net/sonic-platform-common, pull requests merged in 2020-10, with the labels that each got.

#125 [SONIC_SFP] adding support for writing the eeprom address space inside sfputilbase.
  sonic_platform_base/sonic_sfp/sfputilbase.py
Labels: EEPROM, Transceiver

#130 [ChassisBase][ModuleBase] Remove redundant 'get_serial_number()' method
  sonic_platform_base/chassis_base.py
  sonic_platform_base/module_base.py
Labels: Chassis, Cleanup, Module

#132 [sonic_platform_base][fan_drawer_base] adding get_fan definition to the base api definitions of fan_drawer base class
  sonic_platform_base/fan_drawer_base.py
Labels: Fan Drawer

#128 [SONIC_Y_CABLE] Adding new Y cable Package for accessing Y cable QSFP's eeprom and configuring Y cable's mux through eeprom
  setup.py
  sonic_y_cable/__init__.py
  sonic_y_cable/y_cable.py
Labels: EEPROM, Transceiver

#135 [SONIC_Y_CABLE] Fix unpacking of the result returned from read_eeprom API and add missing syslog identifier
  sonic_y_cable/y_cable.py
Labels: EEPROM, Transceiver

#134 [sonic-platform-common] Add new platform API for SONiC Physical MIB Extension feature
  sonic_platform_base/device_base.py
  sonic_platform_base/psu_base.py
  sonic_platform_base/sfp_base.py
Labels: Enhancement, PSU, Transceiver

#137 Add license file
  LICENSE
Labels: Documentation

#138 Add third-party licenses
  ThirdPartyLicenses.txt
Labels: Documentation

#126 [SONIC_SFP] adding abstract methods for reading and writing the eeprom address space within platform api
  sonic_platform_base/sfp_base.py
Labels: EEPROM, Transceiver

#139 Add unit test infrastructure
  .gitignore
  pytest.ini
  setup.cfg
  setup.py
  tests/__init__.py
  tests/sfputilhelper_test.py
  tests/t0-sample-port-config.ini
Labels: Unit Tests

#127 [sonic_eeprom] Make compatible with Python 2 and 3
  sonic_platform_base/sonic_eeprom/eeprom_base.py
  sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
Labels: EEPROM, Enhancement
