Repository sonic-net/sonic-platform-common, pull requests merged in 2021-02, with the labels that each got.

#164 [ci] Test and build packages using Azure Pipelines
  .artifactignore
  azure-pipelines.yml
  pytest.ini
  setup.py
  tests/port_config.ini
  tests/sfputilhelper_test.py
Labels: CI

#166 [ci] Call pip2/3 using sudo
  azure-pipelines.yml
Labels: CI

#167 [GitHub] Add pull request template
  .github/pull_request_template.md
Labels: Documentation

#168 [ci]: download from sonic-buildimage.vs artifact
  azure-pipelines.yml
Labels: CI

#171 [sonic_y_cable] add stub function for upgrade firmware of Y cable and split the get_part_number and get_vendor API's
  sonic_y_cable/y_cable.py
Labels: Cleanup, Enhancement, Y-Cable

#172 [201911][sfputilhelper] Add new option in ports cache creation, fetch ports from config DB
  sonic_platform_base/sonic_sfp/sfputilhelper.py
Labels: Enhancement, Included in 201911 Branch, Transceiver
