Repository sonic-net/sonic-platform-common, pull requests merged in 2021-06, with the labels that each got.

#193 [eeprom_tlv_info] Optimize EEPROM data process by using visitor pattern
  .gitignore
  sonic_platform_base/sonic_eeprom/eeprom_base.py
  sonic_platform_base/sonic_eeprom/eeprom_tlvinfo.py
Labels: EEPROM, Enhancement

#196 Fix typo for midplane APIs.
  sonic_platform_base/module_base.py
Labels: Bug, Chassis

#198 [CI] sonic-config-engine now depends on SONiC YANG packages
  azure-pipelines.yml
Labels: Bug, CI

#194 [sonic_platform/sfp_base] Add common definition for get SFP error status
  sonic_platform_base/sfp_base.py
Labels: Enhancement, Transceiver

#197 Unifying the platform api for get_pcie_aer_stats with PcieBase
  sonic_platform_base/sonic_pcie/pcie_common.py
Labels: Request for 202012 Branch

#199 Fix decode error when parsing EEPROM fields
  sonic_platform_base/sonic_sfp/sffbase.py
Labels: Enhancement, Request for 202012 Branch, Transceiver

#185 Add a template function that returns list of asics on module
  sonic_platform_base/module_base.py
Labels: Enhancement, Module, Multi-ASIC
