Repository sonic-net/sonic-platform-common, pull requests merged in 2021-05, with the labels that each got.

#187 [thermal_manager_base] Add a stop function to thermal manager
  sonic_platform_base/sonic_thermal_control/thermal_manager_base.py
  tests/thermal_manager_test.py
  tests/thermal_policy.json
Labels: Enhancement, Thermal

#188 [sonic_sfp] Handle QSFP DD keys gracefully
  sonic_platform_base/sonic_sfp/qsfp_dd.py
Labels: Bug, Request for 202012 Branch, Transceiver

#189 [component] Add return code constants for FW auto update to component_base
  sonic_platform_base/component_base.py
Labels: Component, Enhancement
