Repository sonic-net/sonic-platform-common, pull requests merged in 2021-11, with the labels that each got.

#229 SSD Health: Retrieve SSD health and temperature values from generic S…
  sonic_platform_base/sonic_ssd/ssd_generic.py
Labels: SSD, Request for 202012 Branch, Request for 202106 Branch

#230 [Y-Cable][Broadcom] upgrade to support Broadcom Y-Cable API to release 1.3
  sonic_y_cable/broadcom/y_cable_broadcom.py
Labels: Request for 202012 Branch

#238 Gracefully handle CMIS APIs for passive modules
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: Bug

#237 [SFP-Refactor] Implement CMIS Low Power mode
  sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
  tests/sonic_xcvr/test_ccmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: Transceiver

#244 Firmware upgrade CLI support for QSFP-DD transceivers
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/api/public/cmisCDB.py
  sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
  tests/sonic_xcvr/test_cmis.py
Labels: Transceiver
