Repository sonic-net/sonic-platform-common, pull requests merged in 2022-05, with the labels that each got.

#268 [CMIS]Fix low-power to high power mode transition
  azure-pipelines.yml
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: Bug, Cleanup

#279 [sonic_ssd] Nokia-7215: "show platform ssdhealth" not showing health percent
  sonic_platform_base/sonic_ssd/ssd_generic.py
  tests/ssd_generic_test.py
Labels: SSD, Request for 202012 Branch, Request for 202111 branch

#280 [Credo][Ycable] changes for synchronizing executing Telemetry API's when mux toggle is inprogress
  sonic_y_cable/credo/y_cable_credo.py
  sonic_y_cable/y_cable_base.py
Labels: Request for 202012 Branch
