Repository sonic-net/sonic-platform-common, pull requests merged in 2022-03, with the labels that each got.

#265 [SSD Generic] Add support for parsing nvme ssd model, health and temperature
  sonic_platform_base/sonic_ssd/ssd_generic.py
  tests/ssd_generic_test.py
Labels: SSD

#267 [xcvr] Add get_module_fw_info method to XcvrApi class.
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
Labels: Bug

#269 [Credo][Ycable] Fix Credo firmware download API download_firmware flag
  sonic_y_cable/credo/y_cable_credo.py
Labels: Request for 202012 Branch

#263 [y_cable][Broadcom] update the BRCM y_cable driver to release 2.0
  sonic_y_cable/broadcom/y_cable_broadcom.py
Labels: Request for 202012 Branch
