Repository sonic-net/sonic-platform-common, pull requests merged in 2023-12, with the labels that each got.

#417 [Credo][Ycable] Correct the lane mapping in the debugdumpregister fun…
  sonic_y_cable/credo/y_cable_credo.py
Labels: Request for 202205 branch, Request for 202211 branch, Request for 202305 branch

#420 [action] [PR:418] Adding supported vendor PNs for remote CDB FW upgrade (#418)
  sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
Labels: automerge

#421 [action] [PR:417] [Credo][Ycable] Correct the lane mapping in the debugdumpregister function for the 50G cable (#417)
  sonic_y_cable/credo/y_cable_credo.py
Labels: automerge

#422 Implementing set_optoe_write_timeout API
  sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
  tests/sonic_xcvr/test_sfp_optoe_base.py
Labels: Transceiver, CMIS, Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch
