Repository sonic-net/sonic-platform-common, pull requests merged in 2023-08, with the labels that each got.

#391 Added new RegBitsFields
  sonic_platform_base/sonic_xcvr/fields/xcvr_field.py
  tests/sonic_xcvr/test_xcvr_field.py
Labels: Transceiver

#390 Add new SSD type support
  sonic_platform_base/sonic_ssd/ssd_generic.py
  tests/ssd_generic_test.py
Labels: Request for 202211 branch, Request for 202305 branch

#384 Apply custom Si settings via CMIS: SONiC xcvrd platform common changes
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: CMIS

#377 Convert the tx/rx power unit to the dBm unit
  sonic_platform_base/sonic_xcvr/api/public/sff8436.py
  sonic_platform_base/sonic_xcvr/api/public/sff8472.py
  sonic_platform_base/sonic_xcvr/api/public/sff8636.py
  tests/sonic_xcvr/test_sff8436.py
  tests/sonic_xcvr/test_sff8472.py
  tests/sonic_xcvr/test_sff8636.py
Labels: CMIS, Request for 202305 branch
