Repository sonic-net/sonic-platform-common, pull requests merged in 2023-11, with the labels that each got.

#411 Correct wrong constant
  sonic_platform_base/sonic_xcvr/fields/consts.py
Labels: C-CMIS

#414 Implement is_copper for SFP
  sonic_platform_base/sonic_xcvr/api/public/sff8472.py
  tests/sonic_xcvr/test_sff8472.py
Labels: Transceiver

#412 Fix issue: QSFP module with id 0x0d can be parsed using 8636
  sonic_platform_base/sonic_xcvr/mem_maps/public/sff8636.py
  sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
  tests/sonic_xcvr/test_xcvr_api_factory.py
Labels: Request for 202305 branch

#402 Fix VDM freeze and unfreeze needed for PM stats collection
  sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
  sonic_platform_base/sonic_xcvr/api/public/cmisVDM.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
  sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
  tests/sonic_xcvr/test_ccmis.py
  tests/sonic_xcvr/test_sfp_optoe_base.py
Labels: C-CMIS
