Repository sonic-net/sonic-platform-common, pull requests merged in 2024-11, with the labels that each got.

#510 Add VDM and Status related cmis fields for onboarding xcvr diagnostic features
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: CMIS, Request for 202405 Branch

#511 [action] [PR:510] Add/modify VDM and Status related cmis fields for onboarding xcvr diagnostic features (#510)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#514 [action] [PR:512] Implement get/set_lpmode API for SFF8472 (#512)
  sonic_platform_base/sonic_xcvr/api/public/sff8472.py
  tests/sonic_xcvr/test_sff8472.py
Labels: automerge

#515 Add diagnostic monitoring APIs for DOM, VDM and status access for CMIS modules
  sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/api/public/cmisVDM.py
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
  sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
  tests/sonic_xcvr/test_cmis.py
  tests/sonic_xcvr/test_cmisVDM.py
  tests/sonic_xcvr/test_sfp_optoe_base.py
Labels: CMIS, C-CMIS

#516 [action] [PR:495] Refactor parse_virtium_info to support new ssd model (#495)
  sonic_platform_base/sonic_storage/ssd.py
  tests/test_ssd.py
Labels: automerge
