Repository sonic-net/sonic-platform-common, pull requests merged in 2024-08, with the labels that each got.

#486 Parse all VDM advertised fields during DOM monitoring
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: CMIS, Request for 202311 Branch, Request for 202405 Branch

#487 [action] [PR:486] Parse all VDM advertised fields during DOM monitoring (#486)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#488 [action] [PR:486] Parse all VDM advertised fields during DOM monitoring (#486)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#483 [202311][SSD] Bug fix: the logic to match the vendor specific attribute is not accurate
  sonic_platform_base/sonic_ssd/ssd_generic.py
  tests/ssd_generic_test.py
Labels: Bug

#492 Use latest natsort package
  setup.py
Labels: Approved for 202405 Branch, Request for 202405 Branch

#494 [action] [PR:492] Use latest natsort package (#492)
  setup.py
Labels: automerge
