Repository sonic-net/sonic-platform-common, pull requests merged in 2024-02, with the labels that each got.

#432 Tx/Rx power values should be rounded up to 3 decimal places
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
Labels: Bug, Request for 202205 Branch, CMIS, Request for 202305 Branch, Request for 202311 Branch

#433 [action] [PR:432] Tx/Rx power values should be rounded up to 3 decimal places (#432)
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
Labels: automerge

#435 [action] [PR:410] APIs to help in finding NPU SI settings (#410)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#434 [action] [PR:422] Implementing set_optoe_write_timeout API (#422)
  sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
  tests/sonic_xcvr/test_sfp_optoe_base.py
Labels: automerge

#437 [action] [PR:432] Tx/Rx power values should be rounded up to 3 decimal places (#432)
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
Labels: automerge

#438 [action] [PR:427] Fix memory map parsing issue (#427)
  sonic_platform_base/sonic_xcvr/codes/public/sff8636.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/sff8636.py
Labels: automerge

#440 Change get_transceiver_info_firmware_versions return type to dict
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: Request for 202205 Branch, CMIS, Request for 202305 Branch, Request for 202311 Branch

#441 [action] [PR:440] Change get_transceiver_info_firmware_versions return type to dict (#440)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#443 [action] [PR:440] Change get_transceiver_info_firmware_versions return type to dict (#440)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#444 [action] [PR:442] Certain VDM fields not populating after encountering KeyError on 400ZR optics (#442)
  sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
  tests/sonic_xcvr/test_ccmis.py
Labels: automerge
