Repository sonic-net/sonic-platform-common, pull requests merged in 2024-05, with the labels that each got.

#462 Handle page select and remote access check after changing SFP target
  sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
  tests/sonic_xcvr/test_cmisTargetFWUpgrade.py
Labels: CMIS, Request for 202305 Branch, Cherry Pick Conflict_202305, Request for 202311 Branch

#463 [action] [PR:450] DPinit timeout seen for Innolight transceiver during CMIS init + transceiver OIR causing CMIS init failure (#450)
  sonic_platform_base/sonic_xcvr/api/innolight/fr_800g.py
  sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
  tests/sonic_xcvr/test_fr_800g.py
  tests/sonic_xcvr/test_xcvr_api_factory.py
Labels: automerge

#464 [action] [PR:455] Fetch firmware versions for Cmis Target FW upgrade supported cables (#455)
  sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/fields/xcvr_field.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
  tests/sonic_xcvr/test_cmisTargetFWUpgrade.py
  tests/sonic_xcvr/test_xcvr_field.py
Labels: automerge

#457 Aligning SONiC code with sff8024 spec
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/codes/public/sff8024.py
  tests/sonic_xcvr/test_cmis.py
Labels: CMIS, Request for 202311 Branch

#461 Update Innolight package for mock test
  setup.py
Labels: Request for 202305 Branch, Request for 202311 Branch

#469 [action] [PR:457] Aligning SONiC code with sff8024 spec (#457)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/codes/public/sff8024.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#468 [action] [PR:462] Handle page select and remote access check after changing SFP target (#462)
  sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
  tests/sonic_xcvr/test_cmisTargetFWUpgrade.py
Labels: automerge

#466 [action] [PR:450] DPinit timeout seen for Innolight transceiver during CMIS init + transceiver OIR causing CMIS init failure (#450)
  sonic_platform_base/sonic_xcvr/api/innolight/fr_800g.py
  sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
  tests/sonic_xcvr/test_fr_800g.py
  tests/sonic_xcvr/test_xcvr_api_factory.py
Labels: automerge

#467 [action] [PR:461] Update Innolight package for mock test (#461)
  setup.py
Labels: automerge

#470 [action] [PR:461] Update Innolight package for mock test (#461)
  setup.py
Labels: automerge

#473 [action] [PR:471] Added API to decommison all datapaths of a CMIS compliant module (#471)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge
