Repository sonic-net/sonic-platform-common, pull requests merged in 2024-04, with the labels that each got.

#453 Separate common code for remote target FW upgrade supported optics
  sonic_platform_base/sonic_xcvr/api/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/codes/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/codes/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/mem_maps/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
Labels: CMIS, Request for 202305 Branch, Request for 202311 Branch

#456 [action] [PR:453] Separate common code for remote target FW upgrade supported optics (#453)
  sonic_platform_base/sonic_xcvr/api/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/codes/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/codes/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/mem_maps/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
Labels: automerge

#458 [action] [PR:453] Separate common code for remote target FW upgrade supported optics (#453)
  sonic_platform_base/sonic_xcvr/api/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/codes/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/codes/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/mem_maps/credo/aec_800g.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
Labels: automerge

#451 Fix the temperature parsing issue on swissbit SSD
  sonic_platform_base/sonic_ssd/ssd_generic.py
Labels: Request for 202311 Branch

#455 Fetch firmware versions for Cmis Target FW upgrade supported cables
  sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/fields/xcvr_field.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
  tests/sonic_xcvr/test_cmisTargetFWUpgrade.py
  tests/sonic_xcvr/test_xcvr_field.py
Labels: CMIS, Request for 202305 Branch, Request for 202311 Branch

#459 [action] [PR:455] Fetch firmware versions for Cmis Target FW upgrade supported cables (#455)
  sonic_platform_base/sonic_xcvr/api/public/cmisTargetFWUpgrade.py
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/fields/xcvr_field.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmisTargetFWUpgrade.py
  tests/sonic_xcvr/test_cmisTargetFWUpgrade.py
  tests/sonic_xcvr/test_xcvr_field.py
Labels: automerge

#460 [action] [PR:451] parse the output from the beginning of the line (#451)
  sonic_platform_base/sonic_ssd/ssd_generic.py
Labels: automerge
