Repository sonic-net/sonic-platform-common, pull requests merged in 2024-09, with the labels that each got.

#491 Make is_flat_memory more robust
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/api/public/sff8436.py
  sonic_platform_base/sonic_xcvr/api/public/sff8472.py
  sonic_platform_base/sonic_xcvr/api/public/sff8636.py
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
Labels: Request for 202405 Branch

#490 [CMIS] Add lane_mask parameter to set_loopback_mode() to enable setti…
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: Cherry Pick Conflict_202311, Request for 202311 Branch, Request for 202405 Branch

#496 [action] [PR:485] [CMIS] Return the CDB status value for the caller to check the status… (#485)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/api/public/cmisCDB.py
  tests/sonic_xcvr/test_cmis.py
  tests/sonic_xcvr/test_cmisCDB.py
Labels: automerge

#498 [action] [PR:475] Fix the temperature parsing in nvme disks (#475)
  sonic_platform_base/sonic_storage/ssd.py
  tests/test_ssd.py
Labels: automerge

#497 [action] [PR:491] Make is_flat_memory more robust (#491)
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/api/public/sff8436.py
  sonic_platform_base/sonic_xcvr/api/public/sff8472.py
  sonic_platform_base/sonic_xcvr/api/public/sff8636.py
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
Labels: automerge

#502 [action] [PR:476] Update additional PN for Innolight and Eoptolink (#476)
  sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
Labels: automerge
