Repository sonic-net/sonic-platform-common, pull requests merged in 2025-06, with the labels that each got.

#576 [action] [PR:557] [Smartswitch] Add module specific pcie attach/detach functions for smartswitch platforms
  sonic_platform_base/module_base.py
  tests/module_base_test.py
Labels: automerge

#562 [cmis] add read only cache decorator
  setup.py
  sonic_platform_base/sfp_base.py
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
  sonic_platform_base/sonic_xcvr/utils/__init__.py
  sonic_platform_base/sonic_xcvr/utils/cache.py
  tests/sonic_xcvr/test_cmis.py
  tests/sonic_xcvr/test_cmis_cache.py
  tests/sonic_xcvr/test_sfp_base.py
Labels: Request for 202411 Branch, Cherry Pick Conflict_202411, Request for msft-202412 Branch, Cherry Pick Conflict_msft-202412, Request for 202505 Branch

#578 [xcvrd] Trim trailing white space in fields of TRANSCEIVER_INFO table
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
Labels: CMIS, Request for msft-202503 Branch, Request for 202505 Branch

#579 [action] [PR:578] [xcvrd] Trim trailing white space in fields of TRANSCEIVER_INFO table
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
Labels: automerge

#583 [action] [PR:580] [cmis] Add delay during CDB firmware download to remove I2C errors
  sonic_platform_base/sonic_xcvr/api/public/cmisCDB.py
Labels: automerge
