Repository sonic-net/sonic-platform-common, pull requests merged in 2025-01, with the labels that each got.

#522 Change Virtium SSD which doesn't support SmartCMD, to use only smartctl
  sonic_platform_base/sonic_storage/ssd.py
Labels: Request for 202405 Branch, Request for 202411 Branch

#531 [action] [PR:522] Change Virtium SSD which doesn't support SmartCMD, to use only smartctl
  sonic_platform_base/sonic_storage/ssd.py
Labels: automerge

#533 Override MaxDurationDPInit through software for values <= 1s
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: CMIS, Cherry Pick Conflict_202405, Request for 202405 Branch, Request for 202411 Branch

#535 [action] [PR:533] Override MaxDurationDPInit through software for values <= 1s
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#526 [cmis] Optimize cmis.get_error_description speed for passive module
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: Request for 202405 Branch, Request for 202411 Branch, Cherry Pick Conflict_202411

#536 [action] [PR:534] [202405] Override MaxDurationDPInit through software for values <= 1s
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: automerge

#527 Create is_transceiver_vdm_supported API for CMIS transceivers
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
  sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
  tests/sonic_xcvr/test_cmis.py
  tests/sonic_xcvr/test_sfp_optoe_base.py
Labels: CMIS
