Repository sonic-net/sonic-platform-common, pull requests merged in 2025-09, with the labels that each got.

#594 [Smartswitch] Restart sensord with lock
  sonic_platform_base/module_base.py
  tests/module_base_test.py
Labels: Request for 202505 Branch, Request for msft-202506 Branch

#595 Fix health check for SSD vendors: add a parser for ATP, and add a generic health ID for other brands
  sonic_platform_base/sonic_storage/ssd.py
  tests/test_ssd.py
Labels: Request for 202505 Branch

#598 [action] [PR:595] Fix health check for SSD vendors: add a parser for ATP, and add a generic health ID for other brands
  sonic_platform_base/sonic_storage/ssd.py
  tests/test_ssd.py
Labels: automerge
