Repository sonic-net/sonic-platform-common, pull requests merged in 2025-05, with the labels that each got.

#556 [cmis] Separate Flag-Specific Fields for DOM and Status APIs
  sonic_platform_base/sonic_xcvr/api/public/c_cmis.py
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/api/public/sff8436.py
  sonic_platform_base/sonic_xcvr/api/public/sff8472.py
  sonic_platform_base/sonic_xcvr/api/public/sff8636.py
  sonic_platform_base/sonic_xcvr/api/xcvr_api.py
  sonic_platform_base/sonic_xcvr/sfp_optoe_base.py
  tests/sonic_xcvr/test_ccmis.py
  tests/sonic_xcvr/test_cmis.py
  tests/sonic_xcvr/test_sff8436.py
  tests/sonic_xcvr/test_sff8472.py
  tests/sonic_xcvr/test_sff8636.py
Labels: CMIS, C-CMIS, Request for msft-202412 Branch

#563 [cmis] combine cmis eeprom i2c read
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
  sonic_platform_base/sonic_xcvr/fields/consts.py
  sonic_platform_base/sonic_xcvr/mem_maps/public/cmis.py
  tests/sonic_xcvr/test_cmis.py
Labels: Request for 202411 Branch, Request for msft-202412 Branch

#566 Fix KeyError for unsupported CMIS applications
  sonic_platform_base/sonic_xcvr/api/public/cmis.py
Labels: Request for msft-202412 Branch

#569 [sonic-platform-common] catch exception while creating api object
  sonic_platform_base/sonic_xcvr/xcvr_api_factory.py
  tests/sonic_xcvr/test_xcvr_api_factory.py
Labels: Request for msft-202412 Branch, Request for 202505 Branch
